# Generated by Django 4.0 on 2021-12-22 19:34

import api.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tradenotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=1000)),
                ('rationale', models.CharField(max_length=1000)),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('last_modified_date', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
                ('emotions', models.CharField(max_length=10)),
                ('media', djongo.models.fields.ArrayField(model_container=api.models.Media, model_form_class=api.models.MediaForm)),
                ('kpis', djongo.models.fields.ArrayField(model_container=api.models.Kpi, model_form_class=api.models.KpiForm)),
                ('trades', djongo.models.fields.ArrayField(model_container=api.models.Trade, model_form_class=api.models.TradeForm)),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
    ]
