# Generated by Django 4.0 on 2021-12-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradenotes',
            name='Profile',
        ),
        migrations.AddField(
            model_name='tradenotes',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
