# Generated by Django 3.1.12 on 2022-07-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tradenotes_title_alter_tradenotes_kpis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradenotes',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
